config/routes.rb
Rails.application.routes.draw do
  scope module: :reginald do
    namespace :av do
      resources :graphs, only: [:index, :create, :destroy]

      resources :shairport_sync, only: [:destroy]
      post "shairport_sync/:id" => "shairport_sync#create"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  around_action :with_singleton

  def with_singleton
    Reginald::AV::System.with_singleton do |system|
      @system = system
      yield
    end
  end

  def system
    @system
  end
  helper_method :system
end

app/controllers/reginald/av/graphs_controller.rb
class Reginald::Av::GraphsController < ApplicationController
  def index
    graphs = system.graphs.sort_by { |g| g.active_path.last.owner.name }
    respond_to do |format|
      format.json { render json: graphs.map(&:as_json) }
      format.html do
        render locals: { graphs: graphs }
      end
    end
  end

  def create
    source = system.devices[params[:source]]
    sink = system.devices[params[:sink]]
    unless source && sink
      return respond_to do |format|
        format.json { render json: { error: "could not find devices" }, status: 404 }
        format.html do
          flash[:error] = "Could not find devices"
          redirect_to :index
        end
      end
    end

    graph = system.build_graph(source, sink)

    # this combo is already playing
    if graph.active_path
      return respond_to do |format|
        format.json { render json: graph.as_json, status: 200 }
        format.html { redirect_to :av_graphs }
      end
    end

    unless params[:interrupt]
      conflicts = graph.conflicting_graphs
      unless conflicts.empty?
        return respond_to do |format|
          format.json { render json: { conflicts: conflicts.map(&:as_json) }, status: 422 }
          format.html do
            flash.now[:error] = "Graph would cause conflict"
            render :index, locals: { graphs: system.graphs }, status: 422
          end
        end
      end
    end

    graph.start(interrupt: params[:interrupt])

    respond_to do |format|
      format.json { render json: graph.as_json, status: 201 }
      format.html { redirect_to :av_graphs }
    end
  end

  def destroy
    graphs = system.graphs.select { |g| g.active_path.last.owner.name == params[:id] }
    if graphs.empty?
      return respond_to do |format|
        format.json { render json: [], status: 404 }
        format.html do
          flash[:error] = "Couldn't find graph"
          redirect_to :av_graphs
        end
      end
    end

    graphs.each(&:stop)

    respond_to do |format|
      format.json { render json: graphs.map(&:as_json) }
      format.html { redirect_to :av_graphs }
    end
  end
end

app/controllers/reginald/av/shairport_sync_controller.rb
# handle events from ShairportSync
class Reginald::Av::ShairportSyncController < ApplicationController
  before_action :find_device
  skip_before_action :verify_authenticity_token

  def create
    return render plain: "Instance Busy", status: 400 unless @device.output_pins.first.graphs.empty?

    return render plain: "Conflict occurred", status: 503 unless @device.start_graphs(system)

    result = 'OK'
    # if we're connected to a virtual matrix, we need to tell Shairport Sync which
    # device we ended up connected to
    pins = @device.output_pins.first.graphs.first&.active_path
    if pins.present? &&
        defined?(Reginald::AV::Devices::VirtualMatrix) &&
        pins[2].owner.is_a?(Reginald::AV::Devices::VirtualMatrix)
      result = pins[2].config['alsa_device'] || 'OK'
    end
    render plain: result
  end

  def destroy
    @device.stop

    render plain: 'OK'
  end

  private

  def find_device
    @device = system.devices[params[:id]]
    return render plain: "Device not found", status: 404 unless @device.is_a?(Reginald::AV::Devices::ShairportSync)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reginald</title>
    <%= csrf_meta_tags %>

    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reginald/av/graphs/index.html.erb
<% if flash[:error] %>
    <h2>Error: <%= flash[:error] %></h2>
<% end %>

<ul>
  <% graphs.each do |graph| %>
    <li><%= graph.active_path.first.owner.description %> is playing on
      <%= graph.active_path.last.owner.name %>
      <%= " (#{graph.volume_pin.volume}#{graph.volume_pin.volume_units})" if graph.volume_pin %>.
      <%= link_to "Stop", av_graph_path(graph.active_path.last.owner.name), method: :delete %></li>
  <% end %>
</ul>
<%= form_tag(:av_graphs, method: :post) do %>
  <%= label_tag(:source, "Source:") %>
  <%= select_tag(:source, options_for_select(system.visible_sources.map { |source| [source.display_name, source.name] }.sort)) %>
  <%= label_tag(:sink, "Sink:") %>
  <%= select_tag(:sink, options_for_select(system.sinks.map(&:name).sort)) %>
  <%= check_box_tag(:interrupt) %>
  <%= label_tag(:interrupt, "Interrupt Active Graphs") %>
  <%= submit_tag("Start") %>
<% end %>